"""rollback

Revision ID: 01e34e916470
Revises: 80c5d62e8497
Create Date: 2026-02-23 13:47:27.031953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01e34e916470'
down_revision = '80c5d62e8497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department_official')
    with op.batch_alter_table('building_department_responsibility', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_building_department_responsibility_building_erp_id'))
        batch_op.drop_index(batch_op.f('ix_building_department_responsibility_department_id'))
        batch_op.drop_index(batch_op.f('ix_building_department_responsibility_official_id'))

    op.drop_table('building_department_responsibility')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building_department_responsibility',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('building_erp_id', sa.INTEGER(), nullable=False),
    sa.Column('department_id', sa.INTEGER(), nullable=False),
    sa.Column('official_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['building_erp_id'], ['geobuilding.erp_id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['official_id'], ['responsible_official.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_erp_id', 'department_id', name=op.f('uq_building_department_one_official'))
    )
    with op.batch_alter_table('building_department_responsibility', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_building_department_responsibility_official_id'), ['official_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_building_department_responsibility_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_building_department_responsibility_building_erp_id'), ['building_erp_id'], unique=False)

    op.create_table('department_official',
    sa.Column('department_id', sa.INTEGER(), nullable=False),
    sa.Column('official_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['official_id'], ['responsible_official.id'], ),
    sa.PrimaryKeyConstraint('department_id', 'official_id')
    )
    # ### end Alembic commands ###
