"""description of position

Revision ID: 02fcdb825f9d
Revises: 18f566dd7d26
Create Date: 2026-04-02 06:57:00.478108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02fcdb825f9d'
down_revision = '18f566dd7d26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_use_unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_of_position', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_use_unit', schema=None) as batch_op:
        batch_op.drop_column('description_of_position')

    # ### end Alembic commands ###
