"""component_hint

Revision ID: 0cc17b16d928
Revises: 69a67d3a3dc7
Create Date: 2026-04-02 08:09:01.537535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc17b16d928'
down_revision = '69a67d3a3dc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component_catalog_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hint', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component_catalog_item', schema=None) as batch_op:
        batch_op.drop_column('hint')

    # ### end Alembic commands ###
