"""is_bool added

Revision ID: 1682d2000df0
Revises: c4411aa3df97
Create Date: 2025-12-11 13:30:49.634307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1682d2000df0'
down_revision = 'c4411aa3df97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component_catalog_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_bool', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component_catalog_item', schema=None) as batch_op:
        batch_op.drop_column('is_bool')

    # ### end Alembic commands ###
