"""vacancy rename

Revision ID: 18f566dd7d26
Revises: 435ed1f57559
Create Date: 2026-04-02 06:50:57.118887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f566dd7d26'
down_revision = '435ed1f57559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_use_unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_vacancy', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_vacant')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_use_unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_vacant', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('is_vacancy')

    # ### end Alembic commands ###
