"""checklist

Revision ID: 1ab8a8cd87f0
Revises: 01e34e916470
Create Date: 2026-02-23 16:22:47.191988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab8a8cd87f0'
down_revision = '01e34e916470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('check_list_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('sub_description', sa.String(length=255), nullable=True),
    sa.Column('ticket_subject', sa.String(length=255), nullable=True),
    sa.Column('ticket_content', sa.Text(), nullable=True),
    sa.Column('dest_erp_user_id', sa.Integer(), nullable=True),
    sa.Column('dest_erp_department_id', sa.Integer(), nullable=True),
    sa.Column('check_list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['check_list_id'], ['check_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('check_list_item')
    op.drop_table('check_list')
    # ### end Alembic commands ###
