"""removed enabled flag from undercomponent

Revision ID: 1bc02f1d43b1
Revises: cb1d6ee3500b
Create Date: 2026-02-20 11:01:10.459033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc02f1d43b1'
down_revision = 'cb1d6ee3500b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('under_component_item', schema=None) as batch_op:
        batch_op.drop_column('enabled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('under_component_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
