"""Raw payload user id

Revision ID: 1c36a89792df
Revises: a15cf5450d3b
Create Date: 2026-03-13 20:26:43.443637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c36a89792df'
down_revision = 'a15cf5450d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_payload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_payload', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
