"""not connect use unit

Revision ID: 2f46a7246e71
Revises: 6038ab3ef1ca
Create Date: 2026-04-02 20:26:53.601517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f46a7246e71'
down_revision = '6038ab3ef1ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_list_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('do_not_connect_use_unit', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_list_item', schema=None) as batch_op:
        batch_op.drop_column('do_not_connect_use_unit')

    # ### end Alembic commands ###
