"""empty message

Revision ID: 32b76b623c3d
Revises: 1e5bf1ea6c73
Create Date: 2025-12-02 13:07:59.748717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b76b623c3d'
down_revision = '1e5bf1ea6c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geolocation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('lon', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geolocation', schema=None) as batch_op:
        batch_op.drop_column('lon')
        batch_op.drop_column('lat')

    # ### end Alembic commands ###
