"""component catalog readonly option

Revision ID: 35fe637dec62
Revises: 9996f2cbbc93
Create Date: 2026-05-26 13:34:53.426417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35fe637dec62'
down_revision = '9996f2cbbc93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component_catalog_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('readonly', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component_catalog_item', schema=None) as batch_op:
        batch_op.drop_column('readonly')

    # ### end Alembic commands ###
