"""check list item enable_dest_contract

Revision ID: 3d1d4489d37b
Revises: 1c36a89792df
Create Date: 2026-03-17 21:41:37.889948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d1d4489d37b'
down_revision = '1c36a89792df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_list_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_dest_contract', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_list_item', schema=None) as batch_op:
        batch_op.drop_column('enable_dest_contract')

    # ### end Alembic commands ###
