"""addition

Revision ID: 435ed1f57559
Revises: 5254ee6d58c8
Create Date: 2026-04-01 13:46:38.683781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435ed1f57559'
down_revision = '5254ee6d58c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_use_unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('erp_contract_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('erp_contract_idnum', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('contract_start', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('contract_end', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_vacant', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_cancelled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_use_unit', schema=None) as batch_op:
        batch_op.drop_column('is_cancelled')
        batch_op.drop_column('is_vacant')
        batch_op.drop_column('contract_end')
        batch_op.drop_column('contract_start')
        batch_op.drop_column('erp_contract_idnum')
        batch_op.drop_column('erp_contract_id')

    # ### end Alembic commands ###
