"""responsibility construct

Revision ID: 484a3a1f8596
Revises: a218d1485b10
Create Date: 2026-02-23 11:42:21.151802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484a3a1f8596'
down_revision = 'a218d1485b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idnum', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geobuilding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('erp_id', sa.Integer(), nullable=False),
    sa.Column('erp_idnum', sa.String(length=100), nullable=False),
    sa.Column('lat', sa.String(length=50), nullable=False),
    sa.Column('lon', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('geobuilding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geobuilding_erp_id'), ['erp_id'], unique=True)

    op.create_table('responsible_official',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short', sa.String(length=50), nullable=True),
    sa.Column('erp_person_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('building_department_responsibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_erp_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('official_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_erp_id'], ['geobuilding.erp_id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['official_id'], ['responsible_official.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_erp_id', 'department_id', name='uq_building_department_one_official')
    )
    with op.batch_alter_table('building_department_responsibility', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_building_department_responsibility_building_erp_id'), ['building_erp_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_building_department_responsibility_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_building_department_responsibility_official_id'), ['official_id'], unique=False)

    op.create_table('department_official',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('official_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['official_id'], ['responsible_official.id'], ),
    sa.PrimaryKeyConstraint('department_id', 'official_id')
    )
    op.drop_table('geolocation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geolocation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('building_id', sa.INTEGER(), nullable=False),
    sa.Column('building_idnum', sa.VARCHAR(length=100), nullable=False),
    sa.Column('lat', sa.VARCHAR(length=50), nullable=False),
    sa.Column('lon', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('department_official')
    with op.batch_alter_table('building_department_responsibility', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_building_department_responsibility_official_id'))
        batch_op.drop_index(batch_op.f('ix_building_department_responsibility_department_id'))
        batch_op.drop_index(batch_op.f('ix_building_department_responsibility_building_erp_id'))

    op.drop_table('building_department_responsibility')
    op.drop_table('responsible_official')
    with op.batch_alter_table('geobuilding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_geobuilding_erp_id'))

    op.drop_table('geobuilding')
    op.drop_table('department')
    # ### end Alembic commands ###
