"""building postcode town

Revision ID: 5254ee6d58c8
Revises: d575cf2cbf41
Create Date: 2026-04-01 12:52:38.800782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5254ee6d58c8'
down_revision = 'd575cf2cbf41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geobuilding', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postcode', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('town', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geobuilding', schema=None) as batch_op:
        batch_op.drop_column('town')
        batch_op.drop_column('postcode')

    # ### end Alembic commands ###
