"""additional balance fields

Revision ID: 52838eca2962
Revises: b5243a599d29
Create Date: 2026-06-19 10:34:33.475041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52838eca2962'
down_revision = 'b5243a599d29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_use_unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance_account', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('balance_positions', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('rent_total', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_use_unit', schema=None) as batch_op:
        batch_op.drop_column('rent_total')
        batch_op.drop_column('balance_positions')
        batch_op.drop_column('balance_account')

    # ### end Alembic commands ###
