"""facility cat enabled view folded

Revision ID: 5bbd0d2fafba
Revises: db4d1b6e4c12
Create Date: 2026-01-28 08:09:01.777127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bbd0d2fafba'
down_revision = 'db4d1b6e4c12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facility_catalog_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view_folded', sa.Boolean(), nullable=True))
        batch_op.drop_column('enabled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facility_catalog_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('view_folded')

    # ### end Alembic commands ###
