"""connect building and eco unit to ticket

Revision ID: 6038ab3ef1ca
Revises: 0cc17b16d928
Create Date: 2026-04-02 15:18:39.886111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6038ab3ef1ca'
down_revision = '0cc17b16d928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_list_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connect_building', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('connect_eco_unit', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_list_item', schema=None) as batch_op:
        batch_op.drop_column('connect_eco_unit')
        batch_op.drop_column('connect_building')

    # ### end Alembic commands ###
