"""UseUnit lookup

Revision ID: 69a67d3a3dc7
Revises: 02fcdb825f9d
Create Date: 2026-04-02 08:05:17.277282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69a67d3a3dc7'
down_revision = '02fcdb825f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('use_unit_type_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Enum('APARTMENT', 'COMMERCIAL', 'GARAGE', 'PARKING', 'OTHER', name='useunittype'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('component_use_unit_type',
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('use_unit_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['component_catalog_item.id'], ),
    sa.ForeignKeyConstraint(['use_unit_type_id'], ['use_unit_type_item.id'], ),
    sa.PrimaryKeyConstraint('component_id', 'use_unit_type_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('component_use_unit_type')
    op.drop_table('use_unit_type_item')
    # ### end Alembic commands ###
