"""dunning

Revision ID: 7b222e2b0da6
Revises: 52838eca2962
Create Date: 2026-06-22 07:57:28.348143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b222e2b0da6'
down_revision = '52838eca2962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_use_unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dunning_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dunning_code', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_use_unit', schema=None) as batch_op:
        batch_op.drop_column('dunning_code')
        batch_op.drop_column('dunning_id')

    # ### end Alembic commands ###
