"""living space

Revision ID: 9048a5934e14
Revises: 7b222e2b0da6
Create Date: 2026-07-08 19:58:47.367963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9048a5934e14'
down_revision = '7b222e2b0da6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_use_unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('living_space', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_use_unit', schema=None) as batch_op:
        batch_op.drop_column('living_space')

    # ### end Alembic commands ###
