"""score and history

Revision ID: 9305839894a3
Revises: e25cce310e84
Create Date: 2026-01-19 15:27:16.728365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9305839894a3'
down_revision = 'e25cce310e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('stamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('use_unit_id', sa.Integer(), nullable=True),
    sa.Column('last_lat', sa.Numeric(), nullable=True),
    sa.Column('last_lon', sa.Numeric(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('facility_catalog_id', sa.Integer(), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('component_catalog_id', sa.Integer(), nullable=True),
    sa.Column('sub_component_ids', sa.String(length=255), nullable=True),
    sa.Column('scorable', sa.Boolean(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_action', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_lat', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('last_lon', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('last_platform', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_version', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_ip', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('enable_score', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('enable_score')
        batch_op.drop_column('last_ip')
        batch_op.drop_column('last_version')
        batch_op.drop_column('last_platform')
        batch_op.drop_column('last_lon')
        batch_op.drop_column('last_lat')
        batch_op.drop_column('last_action')

    op.drop_table('event_item')
    # ### end Alembic commands ###
