"""contract positions fix 2

Revision ID: 95a96783a9b9
Revises: f1e15693bdb6
Create Date: 2026-06-17 21:40:46.269377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95a96783a9b9'
down_revision = 'f1e15693bdb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_position', schema=None) as batch_op:
        batch_op.drop_constraint("contract_position_ibfk_1", type_='foreignkey')
        batch_op.create_foreign_key("fk_erpuseunit_erpid", 'erp_use_unit', ['erp_use_unit_id'], ['erp_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_position', schema=None) as batch_op:
        batch_op.drop_constraint("fk_erpuseunit_erpid", type_='foreignkey')
        batch_op.create_foreign_key("contract_position_ibfk_1", 'erp_use_unit', ['erp_use_unit_id'], ['id'])

    # ### end Alembic commands ###
