"""measure erp id

Revision ID: 9996f2cbbc93
Revises: f769dfe1432a
Create Date: 2026-04-13 07:57:11.824454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9996f2cbbc93'
down_revision = 'f769dfe1432a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mod_prop_measure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('erp_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mod_prop_measure', schema=None) as batch_op:
        batch_op.drop_column('erp_id')

    # ### end Alembic commands ###
