"""Raw Payload route and payload

Revision ID: a15cf5450d3b
Revises: d585441902ed
Create Date: 2026-03-13 20:23:53.270077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a15cf5450d3b'
down_revision = 'd585441902ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_payload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route', sa.String(length=220), nullable=True))
        batch_op.add_column(sa.Column('method', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_payload', schema=None) as batch_op:
        batch_op.drop_column('method')
        batch_op.drop_column('route')

    # ### end Alembic commands ###
