"""checklist item position

Revision ID: a35cf728ace1
Revises: 1ab8a8cd87f0
Create Date: 2026-02-24 07:10:05.145071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a35cf728ace1'
down_revision = '1ab8a8cd87f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_list_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_list_item', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
