"""add microsoft tid and oid

Revision ID: b48004e240e9
Revises: 5bbd0d2fafba
Create Date: 2026-02-09 09:35:47.344996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b48004e240e9'
down_revision = '5bbd0d2fafba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('microsoft_tid', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('microsoft_oid', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_microsoft_oid'), ['microsoft_oid'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_microsoft_tid'), ['microsoft_tid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_microsoft_tid'))
        batch_op.drop_index(batch_op.f('ix_user_microsoft_oid'))
        batch_op.drop_column('microsoft_oid')
        batch_op.drop_column('microsoft_tid')

    # ### end Alembic commands ###
