"""connect use unit

Revision ID: b902bd6e64b4
Revises: 2f46a7246e71
Create Date: 2026-04-02 20:28:00.549827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b902bd6e64b4'
down_revision = '2f46a7246e71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_list_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connect_use_unit', sa.Boolean(), nullable=True))
        batch_op.drop_column('do_not_connect_use_unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_list_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('do_not_connect_use_unit', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('connect_use_unit')

    # ### end Alembic commands ###
