"""typo

Revision ID: b9aaf3ab9ad7
Revises: f7669743a88a
Create Date: 2026-02-26 08:20:23.839585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9aaf3ab9ad7'
down_revision = 'f7669743a88a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_component_names', sa.String(length=255), nullable=True))
        batch_op.drop_column('sub_component_id_names')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_component_id_names', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('sub_component_names')

    # ### end Alembic commands ###
