"""Local Use Units

Revision ID: bbb83c0829e8
Revises: 3d1d4489d37b
Create Date: 2026-03-31 08:12:02.820945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb83c0829e8'
down_revision = '3d1d4489d37b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_use_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('use_unit_type', sa.Enum('APARTMENT', 'COMMERCIAL', 'GARAGE', 'PARKING', 'OTHER', name='useunittype'), nullable=True),
    sa.Column('erp_id', sa.Integer(), nullable=False),
    sa.Column('erp_idnum', sa.String(length=100), nullable=False),
    sa.Column('erp_building_id', sa.Integer(), nullable=False),
    sa.Column('erp_eco_unit_id', sa.Integer(), nullable=False),
    sa.Column('contractor_last_name_1', sa.String(length=200), nullable=True),
    sa.Column('contractor_first_name_1', sa.String(length=200), nullable=True),
    sa.Column('contractor_last_name_2', sa.String(length=200), nullable=True),
    sa.Column('contractor_first_name_2', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('erp_use_unit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_use_unit_erp_id'), ['erp_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_use_unit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_use_unit_erp_id'))

    op.drop_table('erp_use_unit')
    # ### end Alembic commands ###
