"""adding erp facility component catalogs

Revision ID: c4411aa3df97
Revises: 9627eb3b589c
Create Date: 2025-12-09 13:04:18.986071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4411aa3df97'
down_revision = '9627eb3b589c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility_catalog_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('status_name', sa.String(length=50), nullable=True),
    sa.Column('available_economic_unit_land', sa.Boolean(), nullable=True),
    sa.Column('available_building', sa.Boolean(), nullable=True),
    sa.Column('available_use_unit', sa.Boolean(), nullable=True),
    sa.Column('repair_relevance', sa.Boolean(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('custom_name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('under_component_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('custom_name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('component_catalog_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_maintenance_relevant', sa.Boolean(), nullable=True),
    sa.Column('is_repair_relevant', sa.Boolean(), nullable=True),
    sa.Column('is_lease_relevant', sa.Boolean(), nullable=True),
    sa.Column('is_warranty_relevant', sa.Boolean(), nullable=True),
    sa.Column('quantity_type_id', sa.Integer(), nullable=True),
    sa.Column('quantity_type_name', sa.String(length=100), nullable=True),
    sa.Column('quantity_type_code', sa.String(length=100), nullable=True),
    sa.Column('is_metering_device', sa.Boolean(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('custom_name', sa.String(length=200), nullable=True),
    sa.Column('facility_catalog_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facility_catalog_item_id'], ['facility_catalog_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('component_undercomponent',
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('under_component_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['component_catalog_item.id'], ),
    sa.ForeignKeyConstraint(['under_component_id'], ['under_component_item.id'], ),
    sa.PrimaryKeyConstraint('component_id', 'under_component_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('component_undercomponent')
    op.drop_table('component_catalog_item')
    op.drop_table('under_component_item')
    op.drop_table('facility_catalog_item')
    # ### end Alembic commands ###
