"""visibility department

Revision ID: c646018cf30f
Revises: e3ce7eed52c7
Create Date: 2026-02-23 12:31:36.532084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c646018cf30f'
down_revision = 'e3ce7eed52c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visible', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_column('visible')

    # ### end Alembic commands ###
