"""mod prop measures

Revision ID: cbbec643e06b
Revises: b902bd6e64b4
Create Date: 2026-04-12 19:17:57.887017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbbec643e06b'
down_revision = 'b902bd6e64b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mod_prob_measure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mod_prob_measure')
    # ### end Alembic commands ###
