"""raw payload

Revision ID: ce7d4ff5a020
Revises: 1bc02f1d43b1
Create Date: 2026-02-21 07:22:24.866341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce7d4ff5a020'
down_revision = '1bc02f1d43b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_payload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_payload')
    # ### end Alembic commands ###
