"""building lat optional

Revision ID: d575cf2cbf41
Revises: f596db189ef4
Create Date: 2026-04-01 12:45:50.461680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd575cf2cbf41'
down_revision = 'f596db189ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geobuilding', schema=None) as batch_op:
        batch_op.alter_column('lat',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('lon',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geobuilding', schema=None) as batch_op:
        batch_op.alter_column('lon',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('lat',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
