"""facility item

Revision ID: db4d1b6e4c12
Revises: 55c87e700a83
Create Date: 2026-01-22 13:13:22.510822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db4d1b6e4c12'
down_revision = '55c87e700a83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('facility_catalog_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facility_catalog_item_id'], ['facility_catalog_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facility_item')
    # ### end Alembic commands ###
