"""single under component

Revision ID: df38e5b675d5
Revises: 1682d2000df0
Create Date: 2026-01-17 22:28:00.918184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df38e5b675d5'
down_revision = '1682d2000df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component_catalog_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('single_under_component', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component_catalog_item', schema=None) as batch_op:
        batch_op.drop_column('single_under_component')

    # ### end Alembic commands ###
