"""hide quanttity

Revision ID: e25cce310e84
Revises: df38e5b675d5
Create Date: 2026-01-17 22:49:27.638735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e25cce310e84'
down_revision = 'df38e5b675d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component_catalog_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hide_quantity', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component_catalog_item', schema=None) as batch_op:
        batch_op.drop_column('hide_quantity')

    # ### end Alembic commands ###
