"""Rep Off user id

Revision ID: e3ce7eed52c7
Revises: 484a3a1f8596
Create Date: 2026-02-23 12:25:28.897938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ce7eed52c7'
down_revision = '484a3a1f8596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responsible_official', schema=None) as batch_op:
        batch_op.add_column(sa.Column('erp_user_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responsible_official', schema=None) as batch_op:
        batch_op.drop_column('erp_user_id')

    # ### end Alembic commands ###
