"""contract positions

Revision ID: f1e15693bdb6
Revises: 35fe637dec62
Create Date: 2026-06-17 10:07:12.253792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e15693bdb6'
down_revision = '35fe637dec62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('erp_id', sa.Integer(), nullable=False),
    sa.Column('net_amount', sa.Numeric(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('erp_contract_id', sa.Integer(), nullable=False),
    sa.Column('vat_rate_id', sa.Integer(), nullable=False),
    sa.Column('vat_rate_code', sa.String(), nullable=False),
    sa.Column('position_type_id', sa.Integer(), nullable=False),
    sa.Column('position_type_name', sa.String(), nullable=False),
    sa.Column('erp_use_unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['erp_use_unit_id'], ['erp_use_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_position', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_position_erp_id'), ['erp_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_position', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_position_erp_id'))

    op.drop_table('contract_position')
    # ### end Alembic commands ###
