"""building addition

Revision ID: f596db189ef4
Revises: bbb83c0829e8
Create Date: 2026-04-01 12:43:11.037545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f596db189ef4'
down_revision = 'bbb83c0829e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geobuilding', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('street_complete', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('building_type', sa.Enum('LIVING', 'OFFICE', 'PARKING', 'OTHER', name='buildingtype'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geobuilding', schema=None) as batch_op:
        batch_op.drop_column('building_type')
        batch_op.drop_column('street_complete')
        batch_op.drop_column('street')

    # ### end Alembic commands ###
