"""More event info

Revision ID: f7669743a88a
Revises: a35cf728ace1
Create Date: 2026-02-26 08:17:03.623249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7669743a88a'
down_revision = 'a35cf728ace1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_unit_idnum', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('component_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('sub_component_id_names', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_item', schema=None) as batch_op:
        batch_op.drop_column('sub_component_id_names')
        batch_op.drop_column('component_name')
        batch_op.drop_column('use_unit_idnum')

    # ### end Alembic commands ###
